# Konfiguration für das lokale Llama3.1-Modell via Ollama
model: "llama3.1"
model_endpoint: "'http://localhost:11434/v1/'"
model_api_key: "ollama"

# Deine Knowledge Graphs
knowledge_graphs:
  - kg: conference_sofsem
    info:
      endpoint: "http://localhost:7019"
  - kg: conference_ekaw
    info:
      endpoint: "http://localhost:7020"