model: env(MODEL:openai/gpt-4.1)
model_endpoint: env(MODEL_ENDPOINT:null)

api_key: env(API_KEY:null)

fn_set: env(FN_SET:search_extended)

temperature: env(TEMPERATURE:0.2)
top_p: env(TOP_P:0.9)
reasoning_effort: env(REASONING_EFFORT:null)

feedback: env(FEEDBACK:true)
know_before_use: env(KNOW_BEFORE_USE:false)

force_examples: env(FORCE_EXAMPLES:false)
random_examples: env(RANDOM_EXAMPLES:false)

knowledge_graphs:
  - name: wikidata
    endpoint: env(WD_ENDPOINT:null)
  - name: freebase
  - name: dblp
  - name: dbpedia
  - name: imdb
  - name: orkg
  - name: osm-planet
  - name: uniprot

